name: Compile Examples

on:
  push:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - '.github/workflows/compile_library.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/cpp_lint.yml'
      - '.github/workflows/compile_library.yml'

jobs:
  esp8266:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: 
        - "examples/http_upgrade/http_upgrade.ino"
        - "examples/https/https.ino"
        - "examples/mqtt/mqtt.ino"
        - "examples/public_key/public_key.ino"
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Install library
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ESP_SSLClient
        
    - name: update library
      run: |
        pio lib --global update

    - name: Run PlatformIO Examples
      run: |
        pio ci --board=d1_mini \
        --lib=arduino-libraries/ArduinoMqttClient
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}

  esp32:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: 
        - "examples/http_upgrade/http_upgrade.ino"
        - "examples/https/https.ino"
        - "examples/mqtt/mqtt.ino"
        - "examples/public_key/public_key.ino"
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Install library
      run: | 
        pio lib -g install \
        https://github.com/mobizt/ESP_SSLClient
        
    - name: update library
      run: |
        pio lib --global update

    - name: Run PlatformIO Examples
      run: |
        pio ci --board=esp32dev \
        --lib=arduino-libraries/ArduinoMqttClient
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}